### ISSUE TITLE
Support for generating presentable - Delta of New API's URL's/Models/Params etc which got added between different API versions

### ISSUE THREAD

**Issue by rajeshkamal** [civisanalytics/swagger-diff#23]
Support for generating presentable - Delta of New API's URL's/Models/Params etc which got added between different API versions

This Delta can be used in presenting it to the user as new API's since the older version.

**Comment by jeffreyc** [comment]
Generating a list of new endpoints/parameters is not currently supported, but it should be relatively simple, and is something we have talked about adding. However, we're not currently working on that feature, and would welcome a PR adding this functionality.

**Comment by jeffreyc** [comment]
I just released Swagger::Diff 1.1.0. Among other improvements, it adds the a command-line argument to generate a complete list of changes, as opposed to just a list of backwards-incompatible changes.
