### ISSUE TITLE
APIs.guru: showcase and test on real-life APIs

### ISSUE THREAD

**Issue by IvanGoncharov** [civisanalytics/swagger-diff#24]
Hi @jeffreyc,

Maybe you would be interested in testing your tool against 200+ real-life Swagger files:
https://github.com/APIs-guru/api-models
They are validated by [sway](https://github.com/apigee-127/sway/tree/master/docs#swagger-validation) and could accessed through my [REST API](https://github.com/APIs-guru/api-models/blob/master/API.md)(no key needed).

You can also compare different versions of some popular API like Google Drive:
https://apis-guru.github.io/api-models/googleapis.com/drive/v1/swagger.yaml
https://apis-guru.github.io/api-models/googleapis.com/drive/v2/swagger.yaml
https://apis-guru.github.io/api-models/googleapis.com/drive/v3/swagger.yaml
IMHO it will help other developers to see all features of your tool.
All links support CORS so you can use it in online demo.
 
If you have any questions you can ask me directly through Skype(ivangon4arov), Hangout(ivan.goncharov.ua@gmail.com) or you can ask them on public chat: https://gitter.im/APIs-guru/api-models

**Comment by jeffreyc** [comment]
Thanks for the pointer! Those seem like they'd be useful when tackling improvements to the Swagger parser (see https://github.com/civisanalytics/swagger-diff/issues/20#issuecomment-169724830).

**Comment by IvanGoncharov** [comment]
@jeffreyc :+1:
Thanks, I will create similar issue in `swagger-rb`.
