### ISSUE TITLE
Diff fails on identical or very similar schemas 

### ISSUE THREAD

**Issue by zam17** [civisanalytics/swagger-diff#25]
Hello,

I'm getting a failure when comparing two schemas that are identical or very similar.

I'm attaching two schemas that are very similar: swagger1.json and swagger2.json
I've tried running the following commands: 
**1) swagger-diff swagger1.json swagger1.json
2) swagger-diff swagger1.json swagger2.json**

In both cases I'm getting a following error:
**"C:/Ruby21/lib/ruby/gems/2.1.0/gems/swagger-diff-1.0.5/lib/swagger/diff/specifica
tion.rb:109:in `schema': undefined method `allOf' for nil:NilClass (NoMethodErro
r)'**

[swaggerFiles.zip](https://github.com/civisanalytics/swagger-diff/files/117614/swaggerFiles.zip)

**Comment by jeffreyc** [comment]
Thank you for your feedback!

I looked at `swagger1.json`, and the specification appears to be incomplete. You have references (`$ref` keys) to  `#/definitions/Map┬лstring,object┬╗`, but that doesn't appear to be defined anywhere. Swagger::Diff parses definitions recursively, and is failing when it attempts to find the missing definition.

We should probably handle that error in a way that makes it clear what's going wrong, but I think you can resolve your issue by making sure all references are defined. Please let us know if that doesn't resolve your issue, or if you have additional feedback!

**Comment by zam17** [comment]
Thank you very much for help, I've resolved the issue.
