### ISSUE TITLE
Swagger-Diff fails on parsing

### ISSUE THREAD

**Issue by AntonBakaev** [civisanalytics/swagger-diff#38]

**Comment by AntonBakaev** [comment]
Hello,
I'm getting a failure when comparing two files: 
**C:/Ruby23/lib/ruby/2.3.0/json/common.rb:156:in `parse': 784: unexpected token at '{ (JSON::ParserError)**

Error description is poor, so i can't understand where to find an error.
I'm attaching two .json files and error message.
[files.zip](https://github.com/civisanalytics/swagger-diff/files/539056/files.zip)

**Comment by jeffreyc** [comment]
Thank you for your feedback! It looks like there's a syntax error in your JSON, which is causing Swagger::Diff to fail. Using a tool like http://jsonlint.com/, you can see that both files have an unnecessary trailing comma when you close the `DebitInfo` hash. If you remove that (from both files), Swagger::Diff should work correctly.

I'm going to close this issue, but please comment on this issue or file another issue as appropriate if you encounter any other problems with Swagger::Diff.

**Comment by AntonBakaev** [comment]
Thank you very much for help, I was inattentive :) Now I have another problem so I'll create new issue.
