### ISSUE TITLE
All differences are only detected when info.version is equal for compared documents

### ISSUE THREAD

**Issue by tjuchniewicz** [civisanalytics/swagger-diff#44]
Looks like for the same specification using different versions give different results.
Any logic behind that?

**Comment by jeffreyc** [comment]
Thank you for your feedback! Could you elaborate on what you're getting and what you're expecting? Swagger::Diff doesn't take version into consideration, so it's possible there's another culprit. To confirm, I just tried:

- comparing the same specification with a different version
- comparing a specification with a changed attribute and a different version
- comparing a specification with a changed attribute and the same version

and all of the results were as expected.

**Comment by tjuchniewicz** [comment]
@jeffreyc I'm very sorry but I made a mistake when choosing github project... There are two projects with the same name...  
Btw... I'm searching for a swagger diff tool to integrate with Maven...
