### ISSUE TITLE
Differences not being reported by swagger-diff

### ISSUE THREAD

**Issue by gustavlasko** [civisanalytics/swagger-diff#50]
Trying to diff the attached swagger files, I know there are changes, but swagger-diff is reporting none. Running:

gem install swagger-diff
swagger-diff staging-swagger.json dev-swagger.json

Running on windows 8.
[dev-swagger.json.txt](https://github.com/civisanalytics/swagger-diff/files/1243128/dev-swagger.json.txt)
[staging-swagger.json.txt](https://github.com/civisanalytics/swagger-diff/files/1243127/staging-swagger.json.txt)

**Comment by jeffreyc** [comment]
Thanks for the report, and for the examples! It looks like Swagger::Diff doesn't handle the situation where an object has properties (i.e., nested inline objects vs. references). This looks like a 2-line fix (plus tests), so hopefully I can release a bugfix to address this soon.

**Comment by jeffreyc** [comment]
I just released Swagger::Diff 1.1.1, a bugfix release addressing this issue. If you encounter any other problems, please let us know.

**Comment by gustavlasko** [comment]
Thanks for the fast response, I will test it out and let you know if I run
into any issues.
