### ISSUE TITLE
Error regarding /# when diffing swagger

### ISSUE THREAD

**Issue by gustavlasko** [civisanalytics/swagger-diff#54]
Environment:
swagger-diff 1.1.1
Windows 8

Comands:
`gem install swagger-diff`
`swagger-diff -i staging-swagger.json dev-swagger.json` (files have been renamed in order to upload)

Output:
The property '#/' of type string did not match the following type: object in schema http://swagger.io/v2/schema.json#
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/swagger-diff-1.1.1/lib/swagger/diff/specification.rb:73:in `parsed_to_hash': undefined method         `each' for nil:NilClass (NoMethodError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/swagger-diff-1.1.1/lib/swagger/diff/specification.rb:8:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/swagger-diff-1.1.1/lib/swagger/diff/diff.rb:6:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/swagger-diff-1.1.1/lib/swagger/diff/diff.rb:6:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/swagger-diff-1.1.1/exe/swagger-diff:37:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/swagger-diff-1.1.1/exe/swagger-diff:37:in `<top (required)>'
        from C:/Ruby23-x64/bin/swagger-diff:22:in `load'
        from C:/Ruby23-x64/bin/swagger-diff:22:in `<main>'

[dev-swagger.json.txt](https://github.com/civisanalytics/swagger-diff/files/1248795/dev-swagger.json.txt)
[staging-swagger.json.txt](https://github.com/civisanalytics/swagger-diff/files/1248796/staging-swagger.json.txt)

**Comment by jeffreyc** [comment]
Thanks for your feedback! Unfortunately, testing with a clean Ruby 2.3.4 Docker image and the attached specifications, I'm not able to recreate the problem. Could there be an issue with your environment? I can try to test in Windows later, but I have no reason to expect OS-specific limitations.

**Comment by gustavlasko** [comment]
Thanks, I will try on a linux machine and let you know the outcome.

**Comment by gustavlasko** [comment]
I have confirmed, it is something with my environment. It runs fine on linux.
